export const EXCURSIONES_LOADING = 'EXCURSIONES_LOADING';
export const EXCURSIONES_FAILED = 'EXCURSIONES_FAILED';
export const ADD_EXCURSIONES = 'ADD_EXCURSIONES';

export const COMENTARIOS_FAILED = 'COMENTARIOS_FAILED';
export const ADD_COMENTARIOS = 'ADD_COMENTARIOS';

export const CABECERAS_LOADING = 'CABECERAS_LOADING';
export const CABECERAS_FAILED = 'CABECERAS_FAILED';
export const ADD_CABECERAS = 'ADD_CABECERAS';

export const ACTIVIDADES_LOADING = 'ACTIVIDADES_LOADING';
export const ACTIVIDADES_FAILED = 'ACTIVIDADES_FAILED';
export const ADD_ACTIVIDADES = 'ADD_ACTIVIDADES';